
F: np.eye(2)
pD: 0.8
pS: 0.8
S: 10 * np.eye(2)
Q: 30 * np.eye(2)
R: 50 * np.eye(2)
clutter: 1e-6
thrs_T: 1e-4
thrs_U: 0.5
J_max: 100
spawn_params:
  N: 2
  w: 1e-7
  d: np.zeros(2)
  Q: 20 * np.eye(2)
  F: np.eye(2)
birth_params:
  N : 10
  w: 1e-6
  S: 100 * np.eye(2)

